//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)

  /// Find first language and bundle for which the table exists
  fileprivate static func localeBundle(tableName: String, preferredLanguages: [String]) -> (Foundation.Locale, Foundation.Bundle)? {
    // Filter preferredLanguages to localizations, use first locale
    var languages = preferredLanguages
      .map(Locale.init)
      .prefix(1)
      .flatMap { locale -> [String] in
        if hostingBundle.localizations.contains(locale.identifier) {
          if let language = locale.languageCode, hostingBundle.localizations.contains(language) {
            return [locale.identifier, language]
          } else {
            return [locale.identifier]
          }
        } else if let language = locale.languageCode, hostingBundle.localizations.contains(language) {
          return [language]
        } else {
          return []
        }
      }

    // If there's no languages, use development language as backstop
    if languages.isEmpty {
      if let developmentLocalization = hostingBundle.developmentLocalization {
        languages = [developmentLocalization]
      }
    } else {
      // Insert Base as second item (between locale identifier and languageCode)
      languages.insert("Base", at: 1)

      // Add development language as backstop
      if let developmentLocalization = hostingBundle.developmentLocalization {
        languages.append(developmentLocalization)
      }
    }

    // Find first language for which table exists
    // Note: key might not exist in chosen language (in that case, key will be shown)
    for language in languages {
      if let lproj = hostingBundle.url(forResource: language, withExtension: "lproj"),
         let lbundle = Bundle(url: lproj)
      {
        let strings = lbundle.url(forResource: tableName, withExtension: "strings")
        let stringsdict = lbundle.url(forResource: tableName, withExtension: "stringsdict")

        if strings != nil || stringsdict != nil {
          return (Locale(identifier: language), lbundle)
        }
      }
    }

    // If table is available in main bundle, don't look for localized resources
    let strings = hostingBundle.url(forResource: tableName, withExtension: "strings", subdirectory: nil, localization: nil)
    let stringsdict = hostingBundle.url(forResource: tableName, withExtension: "stringsdict", subdirectory: nil, localization: nil)

    if strings != nil || stringsdict != nil {
      return (applicationLocale, hostingBundle)
    }

    // If table is not found for requested languages, key will be shown
    return nil
  }

  /// Load string from Info.plist file
  fileprivate static func infoPlistString(path: [String], key: String) -> String? {
    var dict = hostingBundle.infoDictionary
    for step in path {
      guard let obj = dict?[step] as? [String: Any] else { return nil }
      dict = obj
    }
    return dict?[key] as? String
  }

  static func validate() throws {
    try intern.validate()
  }

  #if os(iOS) || os(tvOS)
  /// This `R.storyboard` struct is generated, and contains static references to 2 storyboards.
  struct storyboard {
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    /// Storyboard `Main`.
    static let main = _R.storyboard.main()

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "Main", bundle: ...)`
    static func main(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.main)
    }
    #endif

    fileprivate init() {}
  }
  #endif

  /// This `R.color` struct is generated, and contains static references to 3 colors.
  struct color {
    /// Color `DividerColour`.
    static let dividerColour = Rswift.ColorResource(bundle: R.hostingBundle, name: "DividerColour")
    /// Color `NavBarColour`.
    static let navBarColour = Rswift.ColorResource(bundle: R.hostingBundle, name: "NavBarColour")
    /// Color `TextColour`.
    static let textColour = Rswift.ColorResource(bundle: R.hostingBundle, name: "TextColour")

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "DividerColour", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func dividerColour(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.dividerColour, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "NavBarColour", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func navBarColour(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.navBarColour, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "TextColour", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func textColour(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.textColour, compatibleWith: traitCollection)
    }
    #endif

    fileprivate init() {}
  }

  /// This `R.file` struct is generated, and contains static references to 1 files.
  struct file {
    /// Resource file `trophies.json`.
    static let trophiesJson = Rswift.FileResource(bundle: R.hostingBundle, name: "trophies", pathExtension: "json")

    /// `bundle.url(forResource: "trophies", withExtension: "json")`
    static func trophiesJson(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.trophiesJson
      return fileResource.bundle.url(forResource: fileResource)
    }

    fileprivate init() {}
  }

  /// This `R.image` struct is generated, and contains static references to 15 images.
  struct image {
    /// Image `Icon_launchscreen`.
    static let icon_launchscreen = Rswift.ImageResource(bundle: R.hostingBundle, name: "Icon_launchscreen")
    /// Image `back_button`.
    static let back_button = Rswift.ImageResource(bundle: R.hostingBundle, name: "back_button")
    /// Image `ellipsis_button`.
    static let ellipsis_button = Rswift.ImageResource(bundle: R.hostingBundle, name: "ellipsis_button")
    /// Image `fast_10k`.
    static let fast_10k = Rswift.ImageResource(bundle: R.hostingBundle, name: "fast_10k")
    /// Image `fast_5k`.
    static let fast_5k = Rswift.ImageResource(bundle: R.hostingBundle, name: "fast_5k")
    /// Image `hakone_ekiden`.
    static let hakone_ekiden = Rswift.ImageResource(bundle: R.hostingBundle, name: "hakone_ekiden")
    /// Image `half_marathon`.
    static let half_marathon = Rswift.ImageResource(bundle: R.hostingBundle, name: "half_marathon")
    /// Image `highest_elevation`.
    static let highest_elevation = Rswift.ImageResource(bundle: R.hostingBundle, name: "highest_elevation")
    /// Image `longest_run`.
    static let longest_run = Rswift.ImageResource(bundle: R.hostingBundle, name: "longest_run")
    /// Image `marathon`.
    static let marathon = Rswift.ImageResource(bundle: R.hostingBundle, name: "marathon")
    /// Image `singapore_ekiden`.
    static let singapore_ekiden = Rswift.ImageResource(bundle: R.hostingBundle, name: "singapore_ekiden")
    /// Image `tokyo_hakone`.
    static let tokyo_hakone = Rswift.ImageResource(bundle: R.hostingBundle, name: "tokyo_hakone")
    /// Image `virtual_10k`.
    static let virtual_10k = Rswift.ImageResource(bundle: R.hostingBundle, name: "virtual_10k")
    /// Image `virtual_5k`.
    static let virtual_5k = Rswift.ImageResource(bundle: R.hostingBundle, name: "virtual_5k")
    /// Image `virtual_half_marathon`.
    static let virtual_half_marathon = Rswift.ImageResource(bundle: R.hostingBundle, name: "virtual_half_marathon")

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "Icon_launchscreen", bundle: ..., traitCollection: ...)`
    static func icon_launchscreen(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.icon_launchscreen, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "back_button", bundle: ..., traitCollection: ...)`
    static func back_button(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.back_button, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "ellipsis_button", bundle: ..., traitCollection: ...)`
    static func ellipsis_button(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.ellipsis_button, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "fast_10k", bundle: ..., traitCollection: ...)`
    static func fast_10k(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.fast_10k, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "fast_5k", bundle: ..., traitCollection: ...)`
    static func fast_5k(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.fast_5k, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "hakone_ekiden", bundle: ..., traitCollection: ...)`
    static func hakone_ekiden(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.hakone_ekiden, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "half_marathon", bundle: ..., traitCollection: ...)`
    static func half_marathon(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.half_marathon, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "highest_elevation", bundle: ..., traitCollection: ...)`
    static func highest_elevation(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.highest_elevation, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "longest_run", bundle: ..., traitCollection: ...)`
    static func longest_run(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.longest_run, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "marathon", bundle: ..., traitCollection: ...)`
    static func marathon(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.marathon, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "singapore_ekiden", bundle: ..., traitCollection: ...)`
    static func singapore_ekiden(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.singapore_ekiden, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "tokyo_hakone", bundle: ..., traitCollection: ...)`
    static func tokyo_hakone(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.tokyo_hakone, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "virtual_10k", bundle: ..., traitCollection: ...)`
    static func virtual_10k(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.virtual_10k, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "virtual_5k", bundle: ..., traitCollection: ...)`
    static func virtual_5k(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.virtual_5k, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "virtual_half_marathon", bundle: ..., traitCollection: ...)`
    static func virtual_half_marathon(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.virtual_half_marathon, compatibleWith: traitCollection)
    }
    #endif

    fileprivate init() {}
  }

  /// This `R.nib` struct is generated, and contains static references to 2 nibs.
  struct nib {
    /// Nib `TrophyCaseHeaderView`.
    static let trophyCaseHeaderView = _R.nib._TrophyCaseHeaderView()
    /// Nib `TrophyCell`.
    static let trophyCell = _R.nib._TrophyCell()

    #if os(iOS) || os(tvOS)
    /// `UINib(name: "TrophyCaseHeaderView", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.trophyCaseHeaderView) instead")
    static func trophyCaseHeaderView(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.trophyCaseHeaderView)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UINib(name: "TrophyCell", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.trophyCell) instead")
    static func trophyCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.trophyCell)
    }
    #endif

    static func trophyCaseHeaderView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> TrophyCaseHeaderView? {
      return R.nib.trophyCaseHeaderView.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? TrophyCaseHeaderView
    }

    static func trophyCell(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> TrophyCell? {
      return R.nib.trophyCell.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? TrophyCell
    }

    fileprivate init() {}
  }

  /// This `R.string` struct is generated, and contains static references to 1 localization tables.
  struct string {
    /// This `R.string.localizable` struct is generated, and contains static references to 16 localization keys.
    struct localizable {
      /// Value: Couldn't load the trophy data.
      static let couldnt_load = Rswift.StringResource(key: "couldnt_load", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Fastest 10K
      static let fast_10k = Rswift.StringResource(key: "fast_10k", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Fastest 5K
      static let fast_5k = Rswift.StringResource(key: "fast_5k", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Hakone Ekiden
      static let hakone_ekiden = Rswift.StringResource(key: "hakone_ekiden", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Half Marathon
      static let half_marathon = Rswift.StringResource(key: "half_marathon", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Highest Elevation
      static let highest_elevation = Rswift.StringResource(key: "highest_elevation", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Longest Run
      static let longest_run = Rswift.StringResource(key: "longest_run", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Marathon
      static let marathon = Rswift.StringResource(key: "marathon", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Mizuno Singapore Ekiden 2020
      static let singapore_ekiden = Rswift.StringResource(key: "singapore_ekiden", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: OK
      static let ok = Rswift.StringResource(key: "ok", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Personal Records
      static let personal_records = Rswift.StringResource(key: "personal_records", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Tokyo-Hakone Ekiden 2020
      static let tokyo_hakone = Rswift.StringResource(key: "tokyo_hakone", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Virtual 10K Race
      static let virtual_10k = Rswift.StringResource(key: "virtual_10k", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Virtual 5K Race
      static let virtual_5k = Rswift.StringResource(key: "virtual_5k", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Virtual Half Marathon Race
      static let virtual_half_marathon = Rswift.StringResource(key: "virtual_half_marathon", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Virtual Races
      static let virtual_races = Rswift.StringResource(key: "virtual_races", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)

      /// Value: Couldn't load the trophy data.
      static func couldnt_load(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("couldnt_load", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "couldnt_load"
        }

        return NSLocalizedString("couldnt_load", bundle: bundle, comment: "")
      }

      /// Value: Fastest 10K
      static func fast_10k(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("fast_10k", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "fast_10k"
        }

        return NSLocalizedString("fast_10k", bundle: bundle, comment: "")
      }

      /// Value: Fastest 5K
      static func fast_5k(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("fast_5k", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "fast_5k"
        }

        return NSLocalizedString("fast_5k", bundle: bundle, comment: "")
      }

      /// Value: Hakone Ekiden
      static func hakone_ekiden(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("hakone_ekiden", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "hakone_ekiden"
        }

        return NSLocalizedString("hakone_ekiden", bundle: bundle, comment: "")
      }

      /// Value: Half Marathon
      static func half_marathon(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("half_marathon", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "half_marathon"
        }

        return NSLocalizedString("half_marathon", bundle: bundle, comment: "")
      }

      /// Value: Highest Elevation
      static func highest_elevation(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("highest_elevation", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "highest_elevation"
        }

        return NSLocalizedString("highest_elevation", bundle: bundle, comment: "")
      }

      /// Value: Longest Run
      static func longest_run(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("longest_run", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "longest_run"
        }

        return NSLocalizedString("longest_run", bundle: bundle, comment: "")
      }

      /// Value: Marathon
      static func marathon(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("marathon", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "marathon"
        }

        return NSLocalizedString("marathon", bundle: bundle, comment: "")
      }

      /// Value: Mizuno Singapore Ekiden 2020
      static func singapore_ekiden(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("singapore_ekiden", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "singapore_ekiden"
        }

        return NSLocalizedString("singapore_ekiden", bundle: bundle, comment: "")
      }

      /// Value: OK
      static func ok(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("ok", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "ok"
        }

        return NSLocalizedString("ok", bundle: bundle, comment: "")
      }

      /// Value: Personal Records
      static func personal_records(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("personal_records", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "personal_records"
        }

        return NSLocalizedString("personal_records", bundle: bundle, comment: "")
      }

      /// Value: Tokyo-Hakone Ekiden 2020
      static func tokyo_hakone(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("tokyo_hakone", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "tokyo_hakone"
        }

        return NSLocalizedString("tokyo_hakone", bundle: bundle, comment: "")
      }

      /// Value: Virtual 10K Race
      static func virtual_10k(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("virtual_10k", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "virtual_10k"
        }

        return NSLocalizedString("virtual_10k", bundle: bundle, comment: "")
      }

      /// Value: Virtual 5K Race
      static func virtual_5k(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("virtual_5k", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "virtual_5k"
        }

        return NSLocalizedString("virtual_5k", bundle: bundle, comment: "")
      }

      /// Value: Virtual Half Marathon Race
      static func virtual_half_marathon(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("virtual_half_marathon", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "virtual_half_marathon"
        }

        return NSLocalizedString("virtual_half_marathon", bundle: bundle, comment: "")
      }

      /// Value: Virtual Races
      static func virtual_races(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("virtual_races", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "virtual_races"
        }

        return NSLocalizedString("virtual_races", bundle: bundle, comment: "")
      }

      fileprivate init() {}
    }

    fileprivate init() {}
  }

  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }

    fileprivate init() {}
  }

  fileprivate class Class {}

  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    #if os(iOS) || os(tvOS)
    try nib.validate()
    #endif
    #if os(iOS) || os(tvOS)
    try storyboard.validate()
    #endif
  }

  #if os(iOS) || os(tvOS)
  struct nib: Rswift.Validatable {
    static func validate() throws {
      try _TrophyCell.validate()
    }

    struct _TrophyCaseHeaderView: Rswift.NibResourceType {
      let bundle = R.hostingBundle
      let name = "TrophyCaseHeaderView"

      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> TrophyCaseHeaderView? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? TrophyCaseHeaderView
      }

      fileprivate init() {}
    }

    struct _TrophyCell: Rswift.NibResourceType, Rswift.Validatable {
      let bundle = R.hostingBundle
      let name = "TrophyCell"

      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> TrophyCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? TrophyCell
      }

      static func validate() throws {
        if UIKit.UIImage(named: "fast_10k", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'fast_10k' is used in nib 'TrophyCell', but couldn't be loaded.") }
        if #available(iOS 11.0, tvOS 11.0, *) {
          if UIKit.UIColor(named: "TextColour", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'TextColour' is used in storyboard 'TrophyCell', but couldn't be loaded.") }
        }
      }

      fileprivate init() {}
    }

    fileprivate init() {}
  }
  #endif

  #if os(iOS) || os(tvOS)
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      #if os(iOS) || os(tvOS)
      try launchScreen.validate()
      #endif
      #if os(iOS) || os(tvOS)
      try main.validate()
      #endif
    }

    #if os(iOS) || os(tvOS)
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UIViewController

      let bundle = R.hostingBundle
      let name = "LaunchScreen"

      static func validate() throws {
        if UIKit.UIImage(named: "Icon_launchscreen", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'Icon_launchscreen' is used in storyboard 'LaunchScreen', but couldn't be loaded.") }
        if #available(iOS 11.0, tvOS 11.0, *) {
          if UIKit.UIColor(named: "NavBarColour", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'NavBarColour' is used in storyboard 'LaunchScreen', but couldn't be loaded.") }
        }
      }

      fileprivate init() {}
    }
    #endif

    #if os(iOS) || os(tvOS)
    struct main: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = NavigationController

      let bundle = R.hostingBundle
      let name = "Main"

      static func validate() throws {
        if #available(iOS 11.0, tvOS 11.0, *) {
          if UIKit.UIColor(named: "NavBarColour", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'NavBarColour' is used in storyboard 'Main', but couldn't be loaded.") }
        }
      }

      fileprivate init() {}
    }
    #endif

    fileprivate init() {}
  }
  #endif

  fileprivate init() {}
}
